<?php
/* comment_form.php
 *     Script for handling shakemap comment submission.  Requires user pass a
 *     CAPTCHA before accepting comment.  Comments are e-mailed to 
 *     $mailRecipient
 *
 * preconditions: includes 'captchaRoutines.php' to provide common interface to
 *                   to the CAPTCHA string routines
 *                imports wp_tt.php wich uses the image generated by
 *                    wp_tt_make.php
 *
 * Operation: the hidden "action" form field is used to direct the script 
 *                from "check" -- verify form inputs
 *                to "display" -- redisplay the form with error indicators
 *                or "success" -- send e-mail and display "thank you" message
 */

    include 'captchaRoutines.php';

    $mailRecipient = "<!-- tmpl_var name="comment-addr" -->";
?>
<html>
    <head>
        <title><!-- tmpl_var name="region" --> ShakeMap: Comment/Questions Form </title>
        <link rel="stylesheet" type="text/css" href="lib/style.css" />

        <?php
            $action = $_POST[action];

            if ($action == "check") {
                $email       = $_POST[email];
                $application = $_POST[application];
                $name        = $_POST['name'];
                $institution = $_POST['inst'];
                $phone       = $_POST['phone'];
                $text        = $_POST['text'];
                $hash        = $_POST['hash'];
                $testword    = strtoupper($_POST['testword']);
                $referer     = $_POST['referer'];

                if (empty($email) ) {
                    $errors[] = "an e-mail address is required";
                } elseif ( ! preg_match("/@/", $email ) ) {
                    $errors[] = "that doesn't look like a valid e-mail address";
                }

                if (empty($name) ) {
                    $errors[] = "please provide a name";
                }

                if (empty($referer) ) {
                    $referer = $_SERVER[HTTP_REFERER];
                    if (empty($referer) ) 
                        $referer = "directy entry/bookmark";
                }

/* since we are verifying human input with CAPTCHA, maybe we don't need this
 *
 *               if (preg_match("/(href|http)/", $text) ) {
 *                   $errors[] = "Sorry, we don't accept comments with links.";
 *               }
 */

                if (!isMatch($hash, $testword) ) {
                    $errors[] = "test code didn't match ";
                }
            }

            $has_errors = count($errors);
 
       // determine what part of the page needs to be displayed:
            if ($action == "") {
               // hitting webpage for the first time, display contents
               $action = "display";
            } elseif ( ($action == check) && $has_errors) {
               // form submitted with errors, redisply content with warnings
               $action = "display";
            } elseif ( ($action = "check") && !$has_errors) {
               // form has been submitted without errors, mail comments
               // and thank submitter
               $mailSubject = "$application comment from $name";
               $text .= "\n\nsubmitted by: $name, $institution, $phone, $email\n";
               $text .= "refered by $referer\n";
               $mailFrom = "From: $name <$email>\r\n";
               mail($mailRecipient, $mailSubject, $text, $mailFrom);
               $action = "success";
            }
        ?>
    </head>
    <body bgcolor="white">

<!-- Begin Tab Header -->
        <table width="100%" border="0" cellspacing="0" cellpadding="7">
            <tr>
                <td bgcolor="ffff99" align="center">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr> 
                            <td width="1%" background="icons/header/tab-begin-lav.gif">&nbsp;</td>
                            <td width="99%"> 
                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                    <tr> 
                                        <td width="30%" align="left">
                                            <table  border="0" cellspacing="0" cellpadding="3">
                                                <tr>
                                                    <td bgcolor="#9999cc"> 
                                                        <div align="center">
                                                            <a href="index.html" class="navbar" onMouseOver="window.status='ShakeMap Home Page';return true">Home</a>
                                                        </div>
                                                    </td>
                                                    <td bgcolor="#9999cc" background="icons/header/tabs-lav.gif">&nbsp;</td>
                                                    <td bgcolor="#9999cc"> 
                                                        <div align="center">
                                                            <a href="archive" class="navbar" onMouseOver="window.status='Archive of Maps for Recent and Historic Earthquakes';return true">Map Archive</a>
                                                        </div>
                                                    </td>
                                                    <td background="icons/header/tab-end-lav.gif">&nbsp;</td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td width="70%" align="right">
                                            <table  border="0" cellspacing="0" cellpadding="3">
                                                <tr>
                                                    <td background="icons/header/tab-begin-lav.gif" align="right">&nbsp;</td>
                                                    <td bgcolor="#9999cc"> 
                                                        <div align="center">
                                                            <a href="links.html" class="navbar" onMouseOver="window.status='Links to ShakeMaps in other regions and other related links';return true">Related Links</a>
                                                        </div>
                                                    </td>
                                                    <td bgcolor="#9999cc" background="icons/header/tabs-lav.gif">&nbsp;</td>
                                                    <td bgcolor="#9999cc"> 
                                                        <div align="center">
                                                            <a href="about.html" class="navbar" onMouseOver="window.status='Information About ShakeMaps';return true">Scientific Background</a>
                                                        </div>
                                                    </td>
                                                    <td bgcolor="#9999cc" background="icons/header/tabs-lav.gif">&nbsp;</td>
                                                    <td bgcolor="#9999cc"> 
                                                        <div align="center">
                                                            <a href="disclaimer.html" class="navbar" onMouseOver="window.status='ShakeMap Disclaimers';return true">Disclaimer</a>
                                                        </div>
                                                    </td>
                                                    <td bgcolor="#9999cc" background="icons/header/tab-left-lav-bgray.gif">&nbsp;</td>
                                                    <td bgcolor="#99cccc"> 
                                                        <div align="center" class="selected">Comment</div>
                                                    </td>
                                                    <td background="icons/header/tab-end-bgray.gif">&nbsp;</td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr> 
                            <td width="1%"  bgcolor="#99cccc">&nbsp;</td>
                            <td width="99%" bgcolor="#99cccc"> 
                                <table border="0" cellspacing="0" cellpadding="3" width="100%">
                                    <tr> 
                                        <td>
                                            <p class="locationbar">Provide Comments on ShakeMap</p>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td width="1%"  bgcolor="#9999cc"><spacer type="block" width="100%" height="1"></td>
                            <td width="99%" bgcolor="#9999cc"><spacer type="block" width="100%" height="1"></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
<!-- End Tab Header -->

        <?php if ($action == "success") { ?>
            <h1>Thanks!</h1>
            <h5>Your comments have been saved and will be reviewed
               by the maintainers of this website.  </h5>
        <?php } else if ($action == "display" ) { ?>

        <p> We welcome your input to improve our
            service and better meet your needs. Please use this form
            to report any problems, ask questions, or provide feedback.
            Please provide at least your e-mail address so that we may
            respond to your comments or questions.
        </p>

        <form method="POST" action="<?php print "$_SERVER[PHP_SELF]"; ?>">
            <?php if ($has_errors) { ?>
                <font size=4 color="red">Please correct the following errors:</font><br />
                    <font color = "red">
                        <ul>
                            <?php
                                foreach ($errors as $val) {
                                    echo "<li>$val</li>";
                                }
                             ?>
                        </ul>
                    </font>
                    <br />

            <?php } else {   // no errors ?>
                <b>please fill out the fields below (required fields are marked with an '*'):</b><br />
            <?php } // end if ($has_errors) ?>
            <input type=hidden name="application" value="shakemap" />
            <input type="hidden" name="action" value="check" />
            <input type="hidden" name="referer" value="<?php print "$referer"; ?>" />
            <table border="0">
                <tr>
                    <td width="140">* Email Address:</td>
                    <td width="500">
                        <input type="text" name="email" size=40 value="<?php print "$email"; ?>" />
                    </td>
                </tr>
                <tr>
                    <td>* Your Name:</td>
                    <td><input type="text" name="name" size=40 value="<?php print "$name"; ?>" /></td>
               </tr>
                <tr>
                    <td>Institution:</td>
                        <td><input type="text" name="inst" size=40 value="<?php print "$institution"; ?>" /></td>
                </tr>
                <tr>
                    <td>Phone #:</td>
                    <td><input type="text" name="phone"  value="<?php print "$phone" ?>"/></td>
                </tr>
            </table>

            <p>Please enter your comments or questions in the box below:
                <br />
                <textarea name="text" rows=15 cols=60><?php print "$text"; ?></textarea>
            </p>

            <?php include 'wp_tt.php'; ?>

            <table border="0">
                <tr>
                    <td width="140">
                        When you are done: 
                    </td>
                    <td width="500">
                        <input type="submit" value="Send Comments" />
                    </td>
                </tr>
                <tr>
                    <td>
                        To clear all input:
                    </td>
                    <td>
                        <input type="reset" value="Clear All Input" />
                    </td>
                </tr>
            </table>
        </form>

        <?php } // end if (success) ?>

        <hr />

        <p>
            <font size="-1">
                Maintained by the ShakeMap Working Group<br />
                Page last modified: $Date: 2006/09/07 20:15:40 $ <br />
            </font>
        </p>

    </body>
</html>
