#       $Id: Makefile 2208 2008-07-03 20:21:27Z klin $     USGS

include ../../../../../include/macros

DIRS = archive\
       event

all install :

clean :
	$(MAKE) -C archive clean
	$(MAKE) -C event clean
